services:
  db:
    build:
      context: ../database
      dockerfile: Dockerfile
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webshop_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webshop_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8082:8080"
    networks:
      - webshop_network

volumes:
  db_data:

networks:
  webshop_network: