services:
  db:
    build:
      context: ../database
      dockerfile: Dockerfile
    network_mode: host
    container_name: mysql_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: webshop_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_PORT=8082  # Override the default port when running in Docker

volumes:
  db_data: